# Generated by Django 4.1.1 on 2022-10-03 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comm_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comm_item', to='auctions.listing'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comm_person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comm_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comm',
        ),
        migrations.AddField(
            model_name='comment',
            name='comm',
            field=models.CharField(default=None, max_length=4048),
        ),
    ]
