# Generated by Django 4.1.1 on 2022-10-04 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_comment_comm_item_comment_comm_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comm_person',
            field=models.ForeignKey(db_column='username', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comm_person', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
