# Generated by Django 4.1.1 on 2022-10-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_bid_first_bid_made'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='first_bid_made',
            field=models.BooleanField(default=None),
        ),
    ]
