# Generated by Django 4.1.2 on 2022-10-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_bid_first_bid_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bid',
            name='starting_bid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bid',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
