# Generated by Django 4.1.2 on 2022-10-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_bid_bid_closed_bid_starting_bid_alter_bid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='starting_bid',
            field=models.FloatField(),
        ),
    ]
