# Generated by Django 4.1.2 on 2022-10-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_bid_starting_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_item',
            field=models.CharField(max_length=64),
        ),
    ]
