# Generated by Django 4.1.2 on 2022-10-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_bid_current_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bid_closed',
            field=models.BooleanField(default=False),
        ),
    ]
